# Generated by Django 3.0.5 on 2020-04-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidrental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='movie_name',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_text',
            field=models.CharField(default='Uncategorized', max_length=200),
        ),
    ]
