# Generated by Django 3.0.5 on 2020-04-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidrental', '0002_auto_20200423_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vidrental.Genre'),
        ),
    ]
