# Generated by Django 3.0.5 on 2020-04-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidrental', '0003_auto_20200424_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_text',
            field=models.CharField(max_length=200),
        ),
    ]
